### ISSUE TITLE
infer issue

### ISSUE THREAD

**Issue by sherifyounis** [BinLiang-NLP/Sentic-GCN#14]
loading word vectors ...
Traceback (most recent call last):
  File "D:\sherif\B thesis\sarcasm paper\import papers\Sentic-GCN-main\ABSA-Detection\infer.py", line 124, in <module>
    inf = Inferer(opt)
  File "D:\sherif\B thesis\sarcasm paper\import papers\Sentic-GCN-main\ABSA-Detection\infer.py", line 55, in __init__     
    embedding_matrix = build_embedding_matrix(self.tokenizer.word2idx, opt.embed_dim, opt.dataset)
  File "D:\sherif\B thesis\sarcasm paper\import papers\Sentic-GCN-main\ABSA-Detection\data_utils.py", line 30, in build_embedding_matrix
    word_vec = load_word_vec(fname, word2idx=word2idx)
  File "D:\sherif\B thesis\sarcasm paper\import papers\Sentic-GCN-main\ABSA-Detection\data_utils.py", line 8, in load_word_vec
    fin = open(path, 'r', encoding='utf-8', newline='\n', errors='ignore')
FileNotFoundError: [Errno 2] No such file or directory: '../glove.42B.300d.txt'

**Comment by fengersenboy** [comment]
下载glove.42B.300d，放到项目文件中

**Comment by BinLiang-NLP** [comment]
> loading word vectors ... Traceback (most recent call last): File "D:\sherif\B thesis\sarcasm paper\import papers\Sentic-GCN-main\ABSA-Detection\infer.py", line 124, in inf = Inferer(opt) File "D:\sherif\B thesis\sarcasm paper\import papers\Sentic-GCN-main\ABSA-Detection\infer.py", line 55, in **init** embedding_matrix = build_embedding_matrix(self.tokenizer.word2idx, opt.embed_dim, opt.dataset) File "D:\sherif\B thesis\sarcasm paper\import papers\Sentic-GCN-main\ABSA-Detection\data_utils.py", line 30, in build_embedding_matrix word_vec = load_word_vec(fname, word2idx=word2idx) File "D:\sherif\B thesis\sarcasm paper\import papers\Sentic-GCN-main\ABSA-Detection\data_utils.py", line 8, in load_word_vec fin = open(path, 'r', encoding='utf-8', newline='\n', errors='ignore') FileNotFoundError: [Errno 2] No such file or directory: '../glove.42B.300d.txt'

Pls download glove.42B.300d.txt and put it in the directory of the project. Thank you!
